# Generated by Django 4.2.11 on 2024-05-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('rarity', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
