# Generated by Django 4.2.11 on 2024-05-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'LEVEL 1'), ('2', 'LEVEL 2'), ('3', 'LEVEL 3'), ('4', 'LEVEL 4'), ('5', 'LEVEL 5'), ('6', 'LEVEL 6'), ('7', 'LEVEL 7'), ('8', 'LEVEL 8'), ('9', 'LEVEL 9'), ('10', 'LEVEL 10'), ('11', 'LEVEL 11'), ('12', 'LEVEL 12'), ('13', 'LEVEL 13'), ('14', 'LEVEL 14')], default='1', max_length=14)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.card')),
            ],
        ),
    ]
