# Generated by Django 4.2.11 on 2024-05-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-date']},
        ),
    ]
