# Generated by Django 4.2.11 on 2024-05-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_player_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='players',
            field=models.ManyToManyField(to='main_app.player'),
        ),
    ]
