# Generated by Django 4.2.11 on 2024-05-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_card_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateField(verbose_name='Upgraded on(example: 2024-05-12)'),
        ),
    ]
